### ISSUE TITLE
🐛 Deployments button lacks link functionality

### ISSUE THREAD

**Issue by TechnoShip123** [TechnoShip123/web-testing#2]
As of commit 06f6d00 in [`web-testing/dev`](https://github.com/TechnoShip123/web-testing/tree/dev), the deployments button does not have link functionality, though the `<a href="">` is present.

**Comment by sjalkote** [comment]
Resolved in commit 6120d92, tested in the [Vercel preview deployment](https://web-testing-9j99lm90m-technoship123.vercel.app/projects/web-testing).
